### PR TITLE
initial commit for backend

### PR DESCRIPTION
**Pull request by about14sheep**
## Describe your changes

* Adds simple setup for backend services. Right now its just a simple echo input server build with Express to keep it simple.
* Adds typescript
* Initial 2 stage dockerfile for building ts modules and running service 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? 
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Review by joshwalters12 — APPROVED** [review]
Looks good as an initial base to work from :)

**Review by chamik — APPROVED** [review]
looks good!

**Review by joao0606almeida — APPROVED** [review]
Looks good!

**Review by Alex1331xela — APPROVED** [review]
Looks good!

**Pull request merged**
